version: '3.1'

services:
  posgresql:
    container_name: posgresql
    image: postgres:9.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: magloirewilly
      POSTGRES_DB: db_centor
    volumes:
      - ./initial.d:/docker-entrypoint-initdb.d
      - ./postgresql/folder/:/var/lib/postgresql/data
    networks:
      - adminer-ntw
      - posgresql-ntw


  centor-api:
    build: .
    container_name: centor-api
    depends_on:
      - posgresql
    ports:
      - 8000:80
    volumes:
      - .:/var/www/app
      - ../data/c-centor:/opt/data/c-centor
      - ./policy.xml:/etc/ImageMagick-6/policy.xml
    environment:
      SYMFONY_ENV: prod
      SYMFONY_DEBUG: 1
      VIRTUAL_HOST: api.cconcours.com, backoffice.cconcours.com
    networks:
        - nginx-proxy
        - posgresql-ntw
        - solr-ntw
    command: sh -c "composer install --no-interaction --prefer-source && chown -R www-data:www-data app/cache && chown -R www-data:www-data app/logs && chown -R www-data:www-data /opt/data/c-centor && /sbin/entrypoint.sh"

networks:
  nginx-proxy:
    external: true
  adminer-ntw:
    external: true
  posgresql-ntw:
    driver: bridge
