version: '3.1'

services:
  posgresql:
    container_name: posgresql
    image: postgres:9.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: magloirewilly
      POSTGRES_DB: db_centor
    volumes:
      - ./initial.d:/docker-entrypoint-initdb.d
      - ./postgresql/folder/:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  solr:
    image: solr:8
    container_name: solr
    ports:
      - "8984:8983"
    volumes:
       - ./solr/data:/var/solr/data

  centor-api:
    build: .
    container_name: centor-api
    depends_on:
      - posgresql
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
    environment:
      SYMFONY_ENV: prod
      SYMFONY_DEBUG: 1
    command: sh -c "composer install --no-interaction --prefer-source && chown -R www-data:www-data app/cache && chown -R www-data:www-data app/logs && /sbin/entrypoint.sh"
