<?php

namespace AppBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{

   /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findList($start=0){
    $qb = $this->createQueryBuilder('s');
       $qb ->orderBy('s.nomConcours', 'asc'); 
    $query=$qb->getQuery();
    $query->setFirstResult($start)->setMaxResults(10);
     return $query->getResult();
}
}
