parameters:
    database_driver: pdo_pgsql
    database_host: 209.50.52.55
    database_port: 5432
    database_name: db_centor
    database_user: postgres
    database_password: magloirewilly
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: d79fccfa0326cb9d214e45c6be226dd58aec74f1
