solr:
    resource: "@SolrBundle/Controller/"
    type:     annotation
    prefix:   /v1

messager:
    resource: "@MessagerBundle/Resources/config/routing.yml"
    prefix:   /v1

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /v1

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /v1
     

user_homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET

download_file:
    path:     /media/{id}/download-file
    defaults: { _controller: "AppBundle:App:download" }
    methods:  GET

download_thumbnail:
    path:     /media/{id}/download-thumbnail
    defaults: { _controller: "AppBundle:App:thumbnail" }
    methods:  GET

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
