
parameters:
#    parameter_name: value
     base_data_dir: /opt/data/c-centor
     my_service_connection: default
     logout.target: /

services:
      fmc_manager:
         class: AppBundle\Service\FMCManager
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


      app.form.registration:
                class: AppBundle\Form\RegistrationType
                tags:
                    - { name: form.type, alias: app_user_registration }

      app.twig_extension:
                class: AppBundle\Twig\AppExtension
                public: false
                tags:
                    - { name: twig.extension }
      create_listener:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: question.created, method: onQuestionCreated }

      file_object_creation_listener:
        class: AppBundle\Event\FileObjectCreationListener
        arguments: ["@doctrine.orm.entity_manager", "@fmc_manager","%base_data_dir%"]
        tags:
          - { name: kernel.event_listener, event: file.object.created, method: onFileObjectCreated }

      app.listener.doctrineevent:
        class: AppBundle\Event\DoctrineEventListener
        arguments: ["@router"]
        tags:
          - { name: doctrine.event_listener, event: postLoad, lazy: true }

      create_user_listener:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: user.created, method: onUserCreated }

      commande_listener:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: commande.confirmed, method: onCommandeConfirmed }

      registration_listener:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: user.registration, method: onRegistration }

      notification_shedule_to_send:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: notification.shedule.to.send, method: onSheduleToSend }

      notification_sended:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: notification.sended, method: onMessageEnd }

      fill_profil_invited:
          class: AppBundle\Event\CreateListener
          arguments: ["@misteio_cloudinary_wrapper","@doctrine.orm.entity_manager", "@twig","@fmc_manager"]
          tags:
            - { name: kernel.event_listener, event: fill.profil.invited, method: onFillProfilInvited }

      app.jmsserializer.datetimeinterface_handler:
        class: SolrBundle\DateTimeInterfaceHandler
        tags:
          - { name: jms_serializer.handler, type: DateTime, direction: serialization, format: json, method: serializeToJson }