Pwm\AdminBundle\Entity\UserAccount:
    exclusion_policy: none
    properties:
        uid:
             groups: ['info','commande', 'full']
        email:
             groups: ['info', 'commande','full']
        displayName:
             groups: ['info','commande', 'full']
        photoURL:
             groups: ['info', 'full']
        phone:
             groups: ['info','commande', 'full']

        ville:
             groups: ['info', 'full']

        langue:
             groups: ['info', 'full']

        branche:
             groups: ['info', 'full']
        serie:
             groups: ['info', 'full']

        niveau:
             groups: ['info', 'full']

        dateMax:
             groups: ['info', 'full']   
             expose: true
             type: DateTime<'Y-m-d'>                         

        paymentMethod:
             groups: ['info', 'full']
             
        enableNotifications:
             groups: ['info', 'full']
