Pwm\AdminBundle\Entity\Ressource:
    exclusion_policy: none
    properties:
        id:
            groups: ['matiere','ressource', 'full']
        description:
             groups: ['matiere','ressource', 'full']
        detail1:
             groups: ['ressource', 'full']    
        detail2:
             groups: ['ressource', 'full']
        style:
             groups: ['ressource', 'full']    
        size:
             groups: ['ressource', 'full']
        nom:
             groups: ['matiere','ressource', 'full'] 
        label:
             groups: ['matiere','ressource', 'full']              
        url:
          access_type: public_method # defaults to property
          accessor: # access_type must be set to public_method
            getter: getUrl
          groups: ['ressource', 'full']
        imageUrl:
          access_type: public_method # defaults to property
          accessor: # access_type must be set to public_method
            getter: getImageUrl
          groups: ['ressource', 'full']
        price:
             groups: ['matiere','full']
