Pwm\AdminBundle\Entity\Abonnement:
    exclusion_policy: none
    properties:
        id:
            groups: ['abonnement', 'full', 'commande']
        studentId:
             groups: ['abonnement', 'full']
        session:
             groups: ['abonnement', 'full']             
        method:
             groups: ['abonnement', 'full']
        plan:
             groups: ['abonnement', 'full']
        status:
             groups: ['abonnement', 'full', 'commande']
        price:
             groups: ['abonnement', 'full']
        startDate:
             groups: ['abonnement', 'full']
             expose: true
             type: DateTime<'Y-m-d'>           
        endDate:
             groups: ['abonnement', 'full']
             expose: true
             type: DateTime<'Y-m-d'> 