AppBundle\Entity\Partie:
    exclusion_policy: none
    properties:
        id:
            groups: ['question','partie', 'full']
        titre:
             groups: ['partie', 'full']
        cours:
          access_type: public_method # defaults to property
          accessor: # access_type must be set to public_method
            getter: getCours
          groups: ['partie', 'full']
        prerequis:
             groups: ['partie', 'full']
        qcm:
             groups: ['partie', 'full']  
        type:
             groups: ['partie', 'full'] 
        analyse:
             groups: ['partie', 'full']  
        article:
             groups: ['partie', 'full']             
        isAvalable:
             groups: ['partie', 'full']   
        sources:
             groups: ['partie', 'full']                                     
        matiere:
             groups: ['partie']
        objectif:
             groups: ['partie', 'full']
    callback_methods:
        pre_serialize: ['getPrerequis','getObjectif','getCours','getQcm']