AppBundle\Entity\Resultat:
    exclusion_policy: none
    properties:
        id:
            groups: ['resultat', 'full']
        url:
          access_type: public_method # defaults to property
          accessor: # access_type must be set to public_method
            getter: getUrl
          groups: ['resultat', 'full']
        description:
             groups: ['resultat', 'full']
        imageUrl:
             groups: ['resultat', 'full']             
        date:
             groups: ['resultat', 'full']
             expose: true
             type: DateTime<'Y-m-d'>      