<?php

namespace Pwm\MessagerBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

  public function findList(){
  	     $startdate=new \DateTime();
         $qb = $this->createQueryBuilder('a')
          ->where('a.type is NULL')
          ->andWhere('a.type =:type')->setParameter('type','public');
          return $qb->getQuery()->setMaxResults(30)->getResult();
  }


}
